<?php

class GDSRDefaults {
    var $default_options = array(
        "version" => "1.9.22",
        "date" => "2012.12.18.",
        "build" => 1171,
        "code_name" => "Prelude",
        "revision" => 0,
        "status" => "Stable",
        "product_id" => "gd-star-rating",
        "admin_views" => 0,
        "bot_message" => "normal",
        "google_rich_snippets_format" => "microformat",
        "google_rich_snippets_active" => 1,
        "google_rich_snippets_datasource" => "standard_rating",
        "google_rich_snippets_hidden" => 0,
        "google_rich_snippets_location" => "bottom",
        "no_votes_percentage" => 100,
        "update_report_usage" => 1,
        "ajax_jsonp" => 0,
        "wp_query_handler" => 1,
        "cached_loading" => 0,
        "prefetch_data" => 1,
        "external_rating_css" => 1,
        "external_css" => 1,
        "css_last_changed" => 0,
        "css_cache_active" => 1,
        "cmm_integration_replay_hide_review" => 0,
        "cmm_integration_prevent_duplicates" => 1,
        "disable_ie6_check" => 0,
        "widgets_hidempty" => 0,
        "encoding" => "UTF-8",
        "news_feed_active" => 1,
        "gfx_generator_auto" => 0,
        "gfx_prevent_leeching" => 1,
        "cache_active" => 1,
        "cache_forced" => 0,
        "cache_cleanup_auto" => 0,
        "cache_cleanup_days" => 7,
        "cache_cleanup_counter" => 0,
        "cache_cleanup_last" => 0,
        "debug_active" => 0,
        "debug_inline" => 1,
        "debug_wpquery" => 0,
        "database_upgrade" => "",
        "database_cleanup" => "",
        "database_cleanup_msg" => "",
        "mass_lock" => "",
        "thumbs_active" => 1,
        "include_opacity" => 0,
        "ie_opacity_fix" => 1,
        "ip_filtering" => 1,
        "ip_filtering_restrictive" => 0,
        "save_user_agent" => 0,
        "save_cookies" => 1,
        "widget_articles" => 1,
        "widget_top" => 1,
        "widget_comments" => 1,
        "security_showip_user_level" => 9,
        "security_showdashboard_user_level" => 9,
        "integrate_post_edit" => 1,
        "integrate_post_edit_mur" => 1,
        "integrate_tinymce" => 1,
        "integrate_dashboard" => 1,
        "integrate_dashboard_latest" => 1,
        "integrate_dashboard_latest_count" => 10,
        "integrate_dashboard_latest_filter_thumb_std" => 1,
        "integrate_dashboard_latest_filter_thumb_cmm" => 1,
        "integrate_dashboard_latest_filter_stars_std" => 1,
        "integrate_dashboard_latest_filter_stars_cmm" => 1,
        "integrate_dashboard_latest_filter_stars_mur" => 1,
        "integrate_rss_powered" => 0,
        "moderation_active" => 0,
        "multis_active" => 1,
        "rss_active" => 0,
        "review_active" => 1,
        "timer_active" => 0,
        "comments_integration_articles_active" => 1,
        "comments_active" => 1,
        "comments_review_active" => 1,
        "thumb_rss_style" => "starrating",
        "thumb_rss_size" => 20,
        "rss_style" => "oxygen",
        "rss_size" => 20,
        "rss_header_text" => "",
        "rss_datasource" => "standard",
        "style" => "oxygen",
        "style_ie6" => "oxygen_gif",
        "size" => 24,
        "stars" => 10,
        "text" => "bottom",
        "align" => "none",
        "header_text" => "",
        "srb_class_block" => "",
        "srb_class_text" => "",
        "srb_class_header" => "",
        "srb_class_stars" => "",
        "cmm_class_block" => "",
        "cmm_class_text" => "",
        "cmm_class_header" => "",
        "cmm_class_stars" => "",
        "default_srb_template" => 0,
        "default_crb_template" => 0,
        "default_ssb_template" => 0,
        "default_mrb_template" => 0,
        "default_tab_template" => 0,
        "default_tcb_template" => 0,
        "mur_style" => "oxygen",
        "mur_style_ie6" => "oxygen_gif",
        "mur_size" => 20,
        "mur_header" => 0,
        "mur_header_text" => "",
        "mur_class_stars" => "",
        "mur_class_block" => "",
        "mur_class_text" => "",
        "mur_class_header" => "",
        "mur_class_button" => "",
        "mur_button_text" => "Submit",
        "mur_button_active" => 1,
        "mur_review_set" => 0,
        "cmm_style" => "oxygen",
        "cmm_style_ie6" => "oxygen_gif",
        "cmm_size" => 16,
        "cmm_stars" => 5,
        "cmm_text" => "bottom",
        "cmm_align" => "none",
        "cmm_header_text" => "",
        "cmm_review_style" => "oxygen",
        "cmm_review_style_ie6" => "oxygen_gif",
        "cmm_review_size" => 20,
        "cmm_review_stars" => 5,
        "cmm_aggr_style" => "oxygen",
        "cmm_aggr_style_ie6" => "oxygen_gif",
        "cmm_aggr_size" => 16,
        "review_style" => "oxygen",
        "review_style_ie6" => "oxygen_gif",
        "review_size" => 20,
        "review_stars" => 5,
        "review_header_text" => "",
        "review_class_block" => "",
        "display_comment" => 1,
        "display_comment_page" => 0,
        "display_posts" => 1,
        "display_pages" => 1,
        "display_home" => 1,
        "display_archive" => 1,
        "display_search" => 1,
        "override_display_comment" => 0,
        "override_thumb_display_comment" => 0,
        "auto_display_position" => "bottom",
        "auto_display_comment_position" => "bottom",
        "thumb_style" => "starrating",
        "thumb_style_ie6" => "starrating_gif",
        "thumb_size" => 20,
        "thumb_header_text" => "",
        "thumb_display_comment" => 1,
        "thumb_display_comment_page" => 0,
        "thumb_display_posts" => 1,
        "thumb_display_pages" => 1,
        "thumb_display_home" => 1,
        "thumb_display_archive" => 1,
        "thumb_display_search" => 1,
        "thumb_auto_display_position" => "bottom",
        "thumb_auto_display_comment_position" => "bottom",
        "thumb_cmm_style" => "starrating",
        "thumb_cmm_style_ie6" => "starrating_gif",
        "thumb_cmm_size" => 20,
        "thumb_cmm_header_text" => "",
        "cookies" => 1,
        "logged" => 1,
        "cmm_cookies" => 1,
        "cmm_logged" => 1,
        "admin_rows" => 10,
        "admin_advanced" => 1,
        "admin_placement" => 1,
        "admin_defaults" => 1,
        "admin_import" => 1,
        "admin_export" => 1,
        "admin_setup" => 1,
        "admin_ips" => 1,
        "author_vote" => 0,
        "cmm_author_vote" => 0,
        "allow_mixed_ip_votes" => 0,
        "cmm_allow_mixed_ip_votes" => 0,
        "mur_allow_mixed_ip_votes" => 0,
        "default_moderation_multis" => "N",
        "default_moderation_articles" => "N",
        "default_moderation_comments" => "N",
        "default_voterules_multis" => "A",
        "default_voterules_articles" => "A",
        "default_voterules_comments" => "A",
        "recc_default_moderation_articles" => "N",
        "recc_default_moderation_comments" => "N",
        "recc_default_voterules_articles" => "A",
        "recc_default_voterules_comments" => "A",
        "default_timer_type" => "N",
        "default_timer_countdown_value" => 30,
        "default_timer_countdown_type" => "D",
        "default_timer_value" => "D30",
        "default_mur_timer_type" => "N",
        "default_mur_timer_countdown_value" => 30,
        "default_mur_timer_countdown_type" => "D",
        "default_mur_timer_value" => "D30",
        "stats_trend_history" => 30,
        "stats_trend_current" => 3,
        "trend_last" => 1,
        "trend_over" => 30,
        "bayesian_minimal" => 10,
        "bayesian_mean" => 70,
        "use_nonce" => 1,
        "int_comment_std_zero" => 0,
        "int_comment_mur_zero" => 0,
        "wait_loader_artthumb" => "flower",
        "wait_loader_cmmthumb" => "flower",
        "wait_loader_article" => "flower",
        "wait_loader_comment" => "flower",
        "wait_loader_multis" => "flower",
        "wait_text_article" => "please wait...",
        "wait_show_article" => 0,
        "wait_class_article" => "",
        "wait_text_comment" => "please wait...",
        "wait_show_comment" => 0,
        "wait_class_comment" => "",
        "wait_text_multis" => "please wait...",
        "wait_show_multis" => 0,
        "wait_class_multis" => ""
    );

    var $function_restrict = array(
        "get_the_excerpt",
        "HS_InlineTags->get_excerpt"
    );

    var $stars_sizes = array("12" => 1, "16" => 1, "20" => 1, "24" => 1, "30" => 1, "46" => 1);

    var $thumb_sizes = array("12" => 1, "16" => 1, "20" => 1, "24" => 1, "32" => 1, "40" => 1);

    var $default_spider_bots = array(
        "FAST", "WebBug", "Spade", "ZyBorg", "rabaz", "Baiduspider", "TechnoratiSnoop", "Rankivabot",
        "Sogou web spider", "WebAlta Crawler", "www.galaxy.com", "Slurp", "msnbot", "appie", "TECNOSEEK",
        "InfoSeek", "WebFindBot", "girafabot", "crawler", "inktomi", "looksmart", "URL_Spider_SQL",
        "Firefly", "NationalDirectory", "Teoma", "alexa", "froogle", "AdsBot-Google", "ia_archiver",
        "Scooter", "Ask Jeeves", "Baiduspider", "Exabot", "FAST Enterprise Crawler", "FAST-WebCrawler",
        "Gigabot", "Mediapartners-Google", "Google Desktop", "Feedfetcher-Google", "Googlebot",
        "heise-IT-Markt-Crawler", "heritrix", "ichiro", "MJ12bot", "MetagerBot", "OmniExplorer_Bot",
        "msnbot-NewsBlogs", "msnbot", "msnbot-media", "NG-Search", "NutchCVS", "Seekbot", "SynooBot",
        "Sensis Web Crawler", "SEO search Crawler", "Seoma", "SEOsearch", "voyager", "W3 SiteSearch Crawler",
        "crawleradmin.t-info@telekom.de", "TurnitinBot", "W3C-checklink", "yacybot", "Yahoo-MMCrawler", 
        "Yahoo! DE Slurp", "Yahoo! Slurp", "YahooSeeker", "Pingdom.com");

    var $shortcodes = array(
        "starrating",
        "starreview",
        "starrater",
        "starratingblock",
        "starratingmulti",
        "starreviewmulti",
        "starcomments",
        "starthumbsblock"
    );

    var $default_wpr8 = array(
        "web_key" => ""
    );

    var $default_import = array(
        "post_star_rating" => 0,
        "wp_post_ratings" => 0,
        "star_rating_for_reviews" => 0,
    );

    var $default_widget_comments = array(
        "title" => "Comments Rating",
        "display" => "all",
        "template_id" => 0,
        "rows" => 5,
        "show" => "total",
        "min_votes" => 1,
        "select" => "post",
        "column" => "rating",
        "order" => "desc",
        "hide_empty" => 1,
        "div_filter" => 0,
        "div_image" => 0,
        "div_stars" => 0,
        "text_max" => 50,
        "rating_stars" => "oxygen",
        "rating_size" => 12,
        "last_voted_days" => 0,
        "avatar" => 40
    );

    var $default_widget_top = array(
        "title" => "Blog Rating",
        "source" => "standard",
        "display" => "all",
        "template_id" => 0,
        "div_template" => "0",
        "div_filter" => "0",
        "div_elements" => "0",
        "select" => "postpage",
        "show" => "total"
    );

    var $default_widget = array(
        "title" => "Rating",
        "source" => "standard",
        "source_set" => 0,
        "template_id" => 0,
        "taxonomy" => "",
        "excerpt_words" => 10,
        "display" => "all",
        "display_categories" => "",
        "rows" => 10,
        "min_votes" => 3,
        "min_count" => 2,
        "select" => "postpage",
        "column" => "rating",
        "order" => "desc",
        "category" => 0,
        "category_toponly" => 1,
        "categories" => "",
        "show" => "total",
        "hide_empty" => 1,
        "hide_noreview" => 0,
        "tpl_title_length" => 0,
        "tpl_encoded" => 1,
        "publish_date" => "alldt",
        "publish_days" => 30,
        "publish_month" => "200808",
        "publish_range_from" => "YYYYMMDD",
        "publish_range_to" => "YYYYMMDD",
        "div_template" => "0",
        "div_filter" => "0",
        "div_trend" => "0",
        "div_elements" => "0",
        "div_image" => "0",
        "div_stars" => "0",
        "grouping" => "post",
        "trends_rating" => "txt",
        "trends_rating_rise" => "+",
        "trends_rating_same" => "=",
        "trends_rating_fall" => "-",
        "trends_rating_set" => "famfamfam",
        "trends_voting" => "txt",
        "trends_voting_rise" => "+",
        "trends_voting_same" => "=",
        "trends_voting_fall" => "-",
        "trends_voting_set" => "famfamfam",
        "bayesian_calculation" => "0",
        "image_resize_x" => 0,
        "image_resize_y" => 0,
        "image_from" => "none",
        "image_custom" => "Image",
        "rating_stars" => "oxygen",
        "rating_size" => 20,
        "rating_thumb" => "starrating",
        "rating_thumb_size" => 20,
        "review_stars" => "oxygen",
        "review_size" => 20,
        "last_voted_days" => 0
    );

    var $default_shortcode_starcomments = array(
        "post" => 0,
        "show" => "total",
        "tpl" => 0
    );

    var $default_shortcode_starreview = array(
        "post" => 0,
        "tpl" => 0,
        "css" => "",
        "style" => "",
        "style_ie6" => "",
        "size" => 0
    );

    var $default_shortcode_starrater = array(
        "post" => 0,
        "tpl" => 0,
        "read_only" => 0,
        "style" => "",
        "style_ie6" => "",
        "size" => 0
    );

    var $default_shortcode_starthumbsblock = array(
        "post" => 0,
        "tpl" => 0,
        "read_only" => 0,
        "style" => "",
        "style_ie6" => "",
        "size" => 0
    );

    var $default_shortcode_starratingmulti = array(
        "id" => 1,
        "tpl" => 0,
        "read_only" => 0,
        "element_stars" => "",
        "element_stars_ie6" => "",
        "element_size" => 0,
        "style" => "oxygen",
        "style_ie6" => "oxygen_gif",
        "size" => 20,
        "average_stars" => "oxygen",
        "average_size" => 30,
        "factor" => 1
    );

    var $default_shortcode_starreviewmulti = array(
        "post" => 0,
        "id" => 1,
        "tpl" => 0,
        "element_stars" => "",
        "element_stars_ie6" => "",
        "element_size" => 0,
        "style" => "oxygen",
        "style_ie6" => "oxygen_gif",
        "size" => 20,
        "average_stars" => "oxygen",
        "average_stars_ie6" => "oxygen_gif",
        "average_size" => 30,
        "factor" => 1
    );

    var $default_shortcode_starrating = array(
        "template_id" => 0,
        "source" => "standard",
        "source_set" => 0,
        "taxonomy" => "",
        "rows" => 10,
        "min_votes" => 3,
        "min_count" => 2,
        "excerpt_words" => 10,
        "select" => "postpage",
        "column" => "rating",
        "order" => "desc",
        "category" => 0,
        "category_toponly" => 1,
        "categories" => "",
        "show" => "total",
        "hide_empty" => 1,
        "hide_noreview" => 0,
        "tpl_title_length" => 0,
        "bayesian_calculation" => "0",
        "publish_date" => "lastd",
        "publish_days" => 0,
        "publish_month" => "200808",
        "publish_range_from" => "YYYYMMDD",
        "publish_range_to" => "YYYYMMDD",
        "div_class" => "",
        "grouping" => "post",
        "trends_rating" => "txt",
        "trends_rating_rise" => "+",
        "trends_rating_same" => "=",
        "trends_rating_fall" => "-",
        "trends_rating_set" => "famfamfam",
        "trends_voting" => "txt",
        "trends_voting_rise" => "+",
        "trends_voting_same" => "=",
        "trends_voting_fall" => "-",
        "trends_voting_set" => "famfamfam",
        "image_resize_x" => 0,
        "image_resize_y" => 0,
        "image_from" => "none",
        "image_custom" => "Image",
        "rating_stars" => "oxygen",
        "rating_size" => 20,
        "rating_thumb" => "starrating",
        "rating_thumb_size" => 20,
        "review_stars" => "oxygen",
        "review_size" => 20,
        "last_voted_days" => 0
    );

    var $default_user_ratings_filter = array(
        "thumb_std" => 1,
        "thumb_cmm" => 1,
        "stars_std" => 1,
        "stars_cmm" => 1,
        "stars_mur" => 1,
        "multis_id" => 0
    );

    var $tables_list = array(
        "data_article",
        "data_category",
        "data_comment",
        "ips",
        "moderate",
        "multis",
        "multis_data",
        "multis_trend",
        "multis_values",
        "templates",
        "votes_log",
        "votes_trend"
    );

    function GDSRDefaults() { }
}

?>